/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Cursor;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import account.Credentials;
import db.DbCommand;

public class ChangeEmail extends javax.swing.JFrame {

	/**
	 * Creates new form ChangeEmail
	 */
	String newEmail;
	
	public ChangeEmail() {
		initComponents();
		l_c_email.setText(new account.Credentials().getEmail());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		t_newEmail = new javax.swing.JTextField();
		b_cancel = new javax.swing.JButton();
		b_submit = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		l_c_email = new javax.swing.JLabel();
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setText(" New Email :-");
		b_cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		b_cancel.setText("Cancel");
		b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				b_cancelMouseClicked(evt);
			}
		});
		b_submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		b_submit.setText("Submit");
		b_submit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				b_submitMouseClicked(evt);
			}
		});
		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(153, 153, 0));
		jLabel2.setText("Change Your Email");
		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel3.setText("Current Email :-");
		l_c_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel3))
						.addGroup(layout.createSequentialGroup().addGap(54, 54, 54).addComponent(b_cancel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addComponent(b_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(33, 33, 33))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(t_newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 248,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(l_c_email, javax.swing.GroupLayout.PREFERRED_SIZE, 248,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(22, 22, 22))))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1))
								.addGroup(layout.createSequentialGroup().addGap(125, 125, 125).addComponent(jLabel2)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel2).addGap(32, 32, 32)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(l_c_email, javax.swing.GroupLayout.PREFERRED_SIZE,
										30, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(t_newEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addGap(52, 52, 52)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(b_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(47, 47, 47)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void b_cancelMouseClicked(java.awt.event.MouseEvent evt) {
		dispose();
	}

	private void b_submitMouseClicked(java.awt.event.MouseEvent evt) {
		newEmail = t_newEmail.getText();
		if (newEmail.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please Your New Enter the email");
		} else {
			verify();
		}

	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChangeEmail().setVisible(true);
			}
		});
	}
	// Variables declaration - do not modify
	private javax.swing.JButton b_cancel;
	private javax.swing.JButton b_submit;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel l_c_email;
	private javax.swing.JTextField t_newEmail;
	// End of variables declaration

	private void verify() {
		if (isEmailValid(newEmail)) {
			this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
			if (isEmailVerified()) {
				db();
			}
			this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
		} else {
			JOptionPane.showMessageDialog(this, "Invalid Email Address");
		}
	}

	boolean isEmailValid(String email) {
		String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\." + "[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
				+ "A-Z]{2,7}$";
		Pattern pat = Pattern.compile(emailRegex);
		if (email == null)
			return false;
		return pat.matcher(email).matches();
	}

	private void db() {
		String current_email = new account.Credentials().getEmail();
		String vr = "####";
		String orignal_pass = new account.Credentials().getPassword();
		String vr_pass = vr.concat(orignal_pass);
		// String opass=vr_pass.substring(4,vr_pass.length());
		String m_email = new Credentials().getModifiedEmail();
		System.out.println(" modified email" + m_email);
		String query1 = "update id_table set password=" + "'" + vr_pass + "' where email='" + current_email + "'";
		String query2 = "update id_table set email=" + "'" + newEmail + "' where password='" + vr_pass + "'";
		String query3 = "update id_table set password=" + "'" + orignal_pass + "' where email='" + newEmail + "'";
		new DbCommand().executeDdlCommand("id", query1);
		new DbCommand().executeDdlCommand("id", query2);
		new DbCommand().executeDdlCommand("id", query3);
		l_c_email.setText(newEmail);
		new Credentials().setCredentials(newEmail, orignal_pass);
		String n_m_email = new Credentials().getModifiedEmail();
		System.out.println("new modified email" + n_m_email);
		String query4 = "rename table " + m_email + " to " + n_m_email;
		new DbCommand().executeDdlCommand("login", query4);
		JOptionPane.showMessageDialog(this, "Email changed Sucessfully");
		this.dispose();
	}

	boolean isEmailVerified() {
		int generatedOTP, enteredOTP;
		generatedOTP = new otp.OTPGenerator().generateOTP();
		System.out.println(generatedOTP);
		new otp.MailOTP(newEmail, generatedOTP);
		String input = JOptionPane.showInputDialog(this, "Enter OTP sent to your mail:");
		try {
			if (input != null) {
				enteredOTP = Integer.parseInt(input);
				if (generatedOTP == enteredOTP) {
					return true;
				} else {
					JOptionPane.showMessageDialog(this, "Entered OTP invalid!! Please check and try again");
				}
			}
		} catch (Exception e) {
			System.out.println(e);
			e.printStackTrace();
		}
		return false;
	}
}