/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

public class MainWin extends javax.swing.JFrame {
	/**
	 * Creates new form MainWin
	 */
	public MainWin() {
		initComponents();
		this.setVisible(true);
		setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/lms.png")));
//		UISetter();
		cursorSetter();
		eventSetter();
		slidesSetter();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jRadioButton1 = new javax.swing.JRadioButton();
		jPanel1 = new javax.swing.JPanel();
		user = new javax.swing.JLabel();
		version_info = new javax.swing.JLabel();
		settings = new javax.swing.JLabel();
		help = new javax.swing.JLabel();
		key = new javax.swing.JLabel();
		lms = new javax.swing.JLabel();
		system_info = new javax.swing.JLabel();
		l_key = new javax.swing.JLabel();
		l_user = new javax.swing.JLabel();
		l_settings = new javax.swing.JLabel();
		l_help = new javax.swing.JLabel();
		l_system_info = new javax.swing.JLabel();
		l_version_info = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		l_info = new javax.swing.JLabel();
		l_sb = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		login_info = new javax.swing.JLabel();
		site_blocker = new javax.swing.JLabel();
		program_blocker = new javax.swing.JLabel();
		l_pb = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jRadioButton1.setText("jRadioButton1");
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("LMS With Parental Controls");
		setResizable(false);
		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
		version_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info.png"))); // NOI18N
		settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/setting.png"))); // NOI18N
		help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
		key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key.png"))); // NOI18N
		lms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lms.png"))); // NOI18N
		system_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/system_info.png"))); // NOI18N
		l_key.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		l_key.setText("Change Password");
		l_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		l_user.setText("Account");
		l_settings.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		l_settings.setText("Settings");
		l_help.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		l_help.setText("Help");
		l_system_info.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		l_system_info.setText("System Info");
		l_version_info.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		l_version_info.setText("Version Info");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(lms)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198,
												Short.MAX_VALUE)
										.addComponent(key).addGap(66, 66, 66))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(l_key).addGap(32, 32, 32)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(user).addComponent(l_user))
						.addGap(35, 35, 35)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(l_settings).addComponent(settings))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(43, 43, 43).addComponent(help)
										.addGap(33, 33, 33))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(l_help).addGap(44, 44, 44)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(system_info)
										.addGap(37, 37, 37).addComponent(version_info))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(l_system_info)
												.addGap(18, 18, 18).addComponent(l_version_info)))
						.addGap(40, 40, 40)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lms)
								.addGroup(jPanel1Layout
										.createSequentialGroup().addGroup(
												jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(key).addComponent(settings).addComponent(help)
														.addComponent(
																user)
														.addComponent(system_info).addComponent(version_info))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGap(0, 0, Short.MAX_VALUE)
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(l_key).addComponent(l_user)
																		.addComponent(l_settings)))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(l_help)
																		.addComponent(l_system_info)
																		.addComponent(l_version_info))
																.addGap(0, 0, Short.MAX_VALUE)))))
								.addContainerGap()));
		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		l_info.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		l_info.setText("Login Info");
		l_sb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		l_sb.setText("Site Blocker");
		login_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login-Info.png"))); // NOI18N
		login_info.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				login_infoMouseClicked(evt);
			}
		});
		site_blocker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/web_blocker-512.png"))); // NOI18N
		program_blocker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/program_block.png"))); // NOI18N
		l_pb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		l_pb.setText("Program Blocker");
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(79, 79, 79).addGroup(jPanel3Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel7).addGap(75, 75, 75))
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(l_sb).addComponent(site_blocker)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(program_blocker).addComponent(l_pb))
						.addGap(62, 62, 62))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(l_info))
								.addComponent(login_info))
						.addGap(379, 379, 379)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(23, 23, 23).addComponent(login_info)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(l_info)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(1, 1, 1)
										.addComponent(program_blocker)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(l_pb).addGap(26, 26, 26))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(site_blocker)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(l_sb).addGap(30, 30, 30)))
						.addComponent(jLabel7).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.setLayout(new java.awt.CardLayout());
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel3,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void login_infoMouseClicked(java.awt.event.MouseEvent evt) {
	}

	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
	void UISetter() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new MainWin().setVisible(true);
//			}
//		});
	}
	// Variables declaration - do not modify
	private javax.swing.JLabel help;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JLabel key;
	private javax.swing.JLabel l_help;
	private javax.swing.JLabel l_info;
	private javax.swing.JLabel l_key;
	private javax.swing.JLabel l_pb;
	private javax.swing.JLabel l_sb;
	private javax.swing.JLabel l_settings;
	private javax.swing.JLabel l_system_info;
	private javax.swing.JLabel l_user;
	private javax.swing.JLabel l_version_info;
	private javax.swing.JLabel lms;
	private javax.swing.JLabel login_info;
	private javax.swing.JLabel program_blocker;
	private javax.swing.JLabel settings;
	private javax.swing.JLabel site_blocker;
	private javax.swing.JLabel system_info;
	private javax.swing.JLabel user;
	private javax.swing.JLabel version_info;
	private javax.swing.JLabel l_img;
	private javax.swing.ImageIcon icon;
	private Timer t;
	private int i = 0;
	// End of variables declaration

	void slidesSetter() {
		l_img = new javax.swing.JLabel();
		String images[] = { "new1.jpg", "new2.jpg", "new3.jpg", "new4.jpg", "new5.jpg" };
		icon = new javax.swing.ImageIcon(getClass().getResource("/icons/welcome.jpg"));
		l_img.setIcon(icon);
		jPanel2.add(l_img);
		t = new Timer(4000, new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (i < images.length) {
					icon = new javax.swing.ImageIcon(getClass().getResource("/icons/" + images[i]));
					l_img.setIcon(icon);
					jPanel2.add(l_img);
				}
				i++;
				if (i >= images.length) {
					i = 0;
				}
			}
		});
		t.start();
	}

	void eventSetter() {
		key.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				boolean isConnected = new net.InternetConnection().isConnected();
				if (isConnected) {
					new account.ResetPassword("");
				}
			}
		});
		user.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				boolean isConnected = new net.InternetConnection().isConnected();
				if (isConnected) {
					new AccountGUI();
				}
			}
		});
		settings.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new SettingsGUI();
			}
		});
		help.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new HelpGUI();
			}
		});
		system_info.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new SystemInfoGUI();
			}
		});
		version_info.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new VersionInfoGUI();
			}
		});
		l_key.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				boolean isConnected = new net.InternetConnection().isConnected();
				if (isConnected) {
					new account.ResetPassword("");
				}
			}
		});
		l_user.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				boolean isConnected = new net.InternetConnection().isConnected();
				if (isConnected) {
					new AccountGUI();
				}
			}
		});
		l_settings.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new SettingsGUI();
			}
		});
		l_help.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new HelpGUI();
			}
		});
		l_system_info.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new SystemInfoGUI();
			}
		});
		l_version_info.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new VersionInfoGUI();
			}
		});
		login_info.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				String tableName = new account.Credentials().getModifiedEmail();
				new LoginInfoTable(tableName);
			}
		});
		site_blocker.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new RunAsAdmin();
			}
		});
		program_blocker.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new PBWindow();
			}
		});
		l_info.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				String tableName = new account.Credentials().getModifiedEmail();
				new LoginInfoTable(tableName);
			}
		});
		l_sb.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new RunAsAdmin();
			}
		});
		l_pb.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				new PBWindow();
			}
		});
	}

	void cursorSetter() {
		key.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		user.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		settings.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		help.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		system_info.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		version_info.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_key.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_user.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_settings.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_help.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_system_info.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_version_info.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		login_info.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		site_blocker.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		program_blocker.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_info.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_sb.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		l_pb.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
	}

	public static void main(String[] args) {
		MainWin mw = new MainWin();
	}
}